mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler400, handler403, handler404, handler500
from personal.api import views as personal_views
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

api_info = openapi.Info(
      title="Brainonet API",
      default_version='v1',
      description="Application API's",
      terms_of_service="https://www.brainonet.com/policies/terms/",
      contact=openapi.Contact(email="contact@brainonet.com"),
      license=openapi.License(name="BSD License"),
   )
schema_view = get_schema_view(
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),

    # REST
    path('api/account/', include('account.api.urls', 'account_api')),
    path('api/blog/', include('blog.api.urls', 'blog_api')),
    path('api/communities/', include('communities.api.urls', 'community_api')),
    path('api/expose/', include('expose.api.urls', 'expose_api')),
    path('api/exposeunits/', include('exposeunits.api.urls', 'exposeunit_api')),
    path('api/personal/', include('personal.api.urls', 'personal_api')),
    path('api/groupchat/', include('groupchat.api.urls', 'groupchat_api')),
    path('api/recommend/', include('recommend.api.urls', 'recommendation_api')),
    path('api/commons/', include('commons.api.urls', 'commons_api')),

    # path('api/', schema_view),

    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    # AutoComplete
    # re_path(r'^select2/', include('django_select2.urls')),

]

handler400 = personal_views.error_400
handler404 = personal_views.error_404
handler403 = personal_views.error_403
handler500 = personal_views.error_500

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal/api/urls.py
from django.urls import re_path, path, include
from .views import *
from blog.api.views import ApiReferenceListView, ApiBlogListView
from communities.api.views import ApiCommunityListView

app_name = "personal"

urlpatterns = [

    re_path(r"^$", stafflogin_view, name="staff_login"),
    re_path(r"^staffhome/$", staffhome_view, name="staff_home"),

    re_path(r"^staffhome/blog-manager/$", blog_manager_view, name="blog_manager"),
    re_path(r"^staffhome/community-manager/$", community_manager_view, name="community_manager"),
    re_path(r"^staffhome/reference-manager/$", reference_manager_view, name="reference_manager"),

    re_path(r"^staffhome/addblog/$", uploadblog, name="add_blog"),
    re_path(r"^staffhome/addreferences/$", uploadreferences, name="add_references"),
    re_path(r"^staffhome/addcommunity/$", uploadcommunity, name="add_community"),

    # re_path(r"^staffhome/showblogs/$", BlogHomeView.as_view(), name="show_blog"),
    # re_path(r"^staffhome/showcommunity/$", CommunityHomeView.as_view(), name="show_community"),
    re_path(r"^staffhome/showaccounts/$", UserListView.as_view(), name="show_account"),

    re_path(r"staffhome/editblog/(?P<slug>[\w-]+)/", BlogUpdateView.as_view(), name="edit_blog"),
    re_path(r"staffhome/deleteblog/(?P<slug>[\w-]+)/", BlogDeleteView.as_view(), name="delete_blog"),
    re_path(r"staffhome/editcommunity/(?P<slug>[\w-]+)/", CommunityUpdateView.as_view(), name="edit_community"),
    re_path(r"staffhome/deletecommunity/(?P<slug>[\w-]+)/", CommunityDeleteView.as_view(), name="delete_community"),
    re_path(r"staffhome/editreference/(?P<pk>[\w-]+)/", ReferenceUpdateView.as_view(), name="edit_reference"),
    re_path(r"staffhome/deletereference/(?P<pk>[\w-]+)/", ReferenceDeleteView.as_view(), name="delete_reference"),

    re_path(r"staffhome/communityhistory/(?P<slug>[\w-]+)/", CommunityHistoryView.as_view(), name="community_history"),
    re_path(r"staffhome/bloghistory/(?P<slug>[\w-]+)/", BlogHistoryView.as_view(), name="blog_history"),
    re_path(r"staffhome/referencehistory/(?P<pk>[\w-]+)/", ReferenceHistoryView.as_view(), name="reference_history"),

    re_path(r"staffhome/logout", stafflogout, name="staff_logout"),
    re_path(r"^staffhome/users_autocomplete/$", UsersAutocomplete.as_view(), name="users_autocomplete"),
    re_path(r"^staffhome/references_autocomplete/$", ReferencesAutocomplete.as_view(create_field='refers'),
            name="references_autocomplete"),

    re_path(r"^staffhome/imagefaketool$", fakenews_home, name="fake_toolkit"),
    re_path(r"^staffhome/imagefakesearch$", fakenews_image_search, name="fake_image_search"),
    re_path(r"^staffhome/imagedataset$", fakenews_image_dataset, name="fake_image_dataset"),

    re_path(r"^staffhome/staff-manager/$", staff_manager_view, name="staff_manager"),
    re_path(r"^staffhome/addstaff/$", addstaff, name="add_staff"),
    re_path(r"^staffhome/staff_autocomplete_mobile/$", StaffAutocompleteMobile.as_view(), name="staff_autocomplete_mobile"),
    re_path(r"^staffhome/staff_autocomplete_fname/$", StaffAutocompleteFname.as_view(), name="staff_autocomplete_fname"),
    re_path(r"^staffhome/staff_autocomplete_lname/$", StaffAutocompleteLname.as_view(), name="staff_autocomplete_lname"),
    re_path(r"^staffhome/staff-remove/(?P<pk>[\w-]+)$", staff_delete_view, name="staff_remove"),
    re_path(r"^staffhome/staff-list/$", ApiStaffListView.as_view(), name="staff-list"),

    # CORS not working, this is a hack so that cookie is passed to same domain for ajax
    re_path(r"^staffhome/blog-list$", ApiBlogListView.as_view(), name="blog-list"),
    re_path(r"^staffhome/reference-list$", ApiReferenceListView.as_view(), name="reference-list"),
    re_path(r"^staffhome/community-list$", ApiCommunityListView.as_view(), name="community-list"),

]

personal/models.py
from django.db import models

# Create your models here.

personal/api/views.py
from django.views import generic
from personal.api import form
from blog.models import Blog, References, BlogHistory, ReferenceHistory
from communities.models import Communities, CommunityHistory
from account.models import TokenAuthentication
from .form import BlogForm, CommunityForm, ReferencesForm
from .filters import StaffSearchFilter
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect, render
from django.shortcuts import Http404, HttpResponse
from django.http import HttpResponseRedirect
from account.models import Account, Token
from dal import autocomplete
from account.api.form import MobileForm, OtpForm
from rest_framework.views import APIView
from rest_framework.decorators import api_view, permission_classes
from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer
from utilities.imsearch import colordescriptor, searcher, createdataset
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages
from rest_framework.response import Response
import cv2
import logging
from personal.utils import get_token_from_cookie, get_opencv_img_from_buffer, get_image_search_results
from account.permissions import IsStaff, IsManager, IsAdministrator
from rest_framework.generics import ListAPIView
from .serializers import StaffDisplaySerializer
from rest_framework.pagination import PageNumberPagination
from rest_framework.filters import SearchFilter, OrderingFilter

logger = logging.getLogger(__name__)


def stafflogin_view(request):
    context = {}
    context['mobileForm'] = MobileForm
    context['otpForm'] = OtpForm
    return render(request, 'staffapplication/login.html', context)


@api_view(["GET"])
@permission_classes([IsStaff])
def staffhome_view(request):
    context = {}
    context['response'] = _("response.success")
    return render(request, "staffapplication/home.html", context)


@api_view(["GET"])
@permission_classes([IsStaff])
def blog_manager_view(request):
    context = {}
    logger.info(request.query_params)
    logger.info(request.GET)
    context['response'] = _("response.success")
    context['blogForm'] = form.BlogForm
    # for session storage based back button
    if request.GET.get('back', False):
        context['back'] = True
    return render(request, "staffapplication/pages/managers/blog-manager.html", context)


@api_view(["GET"])
@permission_classes([IsStaff])
def staff_manager_view(request):
    context = {}
    logger.info(request.query_params)
    logger.info(request.GET)
    context['response'] = _("response.success")
    context['staffCreateForm'] = form.StaffCreateForm(initial={'is_staff': True})
    context['staffRemoveForm'] = form.StaffRemoveForm

    # for session storage based back button
    if request.GET.get('back', False):
        context['back'] = True
    return render(request, "staffapplication/pages/managers/staff-manager.html", context)


@api_view(["GET"])
@permission_classes([IsStaff])
def community_manager_view(request):
    context = {}
    context['response'] = _("response.success")
    context['communityForm'] = form.CommunityForm
    # for session storage based back button
    if request.GET.get('back', False):
        context['back'] = True
    return render(request, "staffapplication/pages/managers/community-manager.html", context)


@api_view(["GET"])
@permission_classes([IsStaff])
def reference_manager_view(request):
    context = {}
    context['response'] = _("response.success")
    context['referenceForm'] = form.ReferencesForm
    # for session storage based back button
    if request.GET.get('back', False):
        context['back'] = True
    return render(request, "staffapplication/pages/managers/reference-manager.html", context)


class BlogHistoryView(generic.ListView, APIView):
    permission_classes = [IsStaff]
    model = Blog
    template_name = "staffapplication/pages/managers/update-job/content-history.html"
    context_object_name = "changeCollection"
    paginate_by = 10

    def get_queryset(self):
        history = BlogHistory.objects.filter(blogid=self.kwargs['slug'])
        return history

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blogback'] = True
        return context


class BlogUpdateView(generic.UpdateView):
    permission_classes = [IsStaff]
    model = Blog
    # fields = ['title', 'references', 'description', 'body', 'image', 'community']
    template_name = "staffapplication/pages/managers/update-job/update-form.html"
    success_url = reverse_lazy('personal:blog_manager')
    form_class = BlogForm

    def post(self, request, *args, **kwargs):
        token = get_token_from_cookie(request)
        try:
            token = Token.objects.get(key=token)
            request.user = token.user
            return super(BlogUpdateView, self).post(request, **kwargs)
        except Token.DoesNotExist:
            return HttpResponse("response.401", status=401)

    def form_valid(self, form):
        self.object = form.save()
        BlogHistory(blogid=self.object.slug, user=self.request.user, job='U').save()
        messages.add_message(self.request, messages.SUCCESS, "Blog Updated Successfuly")
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blogback'] = True
        return context


class BlogDeleteView(generic.DeleteView, APIView):
    permission_classes = [IsStaff]
    model = Blog
    success_url = reverse_lazy('personal:blog_manager')
    template_name = "staffapplication/pages/managers/update-job/confirm-delete.html"

    def delete(self, request, *args, **kwargs):
        # self.object = form.save()
        self.object = self.get_object()
        success_url = self.get_success_url()
        BlogHistory(blogid=self.object.slug, user=self.request.user, job='D').save()
        self.object.delete()
        return HttpResponseRedirect(success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blogback'] = True
        return context


class CommunityHistoryView(generic.ListView, APIView):
    permission_classes = [IsStaff]
    model = Communities
    template_name = "staffapplication/pages/managers/update-job/content-history.html"
    context_object_name = "changeCollection"
    paginate_by = 10

    def get_queryset(self):
        history = CommunityHistory.objects.filter(communityid=self.kwargs['slug'])
        return history

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['communityback'] = True
        return context


class CommunityUpdateView(generic.UpdateView):
    permission_classes = [IsStaff]
    model = Communities
    # fields = ['title', 'references', 'description', 'body', 'image', 'community']
    template_name = "staffapplication/pages/managers/update-job/update-form.html"
    success_url = reverse_lazy('personal:community_manager')
    form_class = CommunityForm

    def post(self, request, *args, **kwargs):
        token = get_token_from_cookie(request)
        try:
            token = Token.objects.get(key=token)
            request.user = token.user
            return super(CommunityUpdateView, self).post(request, **kwargs)
        except Token.DoesNotExist:
            return HttpResponse("response.401", status=401)

    def form_valid(self, form):
        self.object = form.save()
        CommunityHistory(communityid=self.object.slug, user=self.request.user, job='U').save()
        messages.add_message(self.request, messages.SUCCESS, "Community Updated Successfuly")
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['communityback'] = True
        return context


class CommunityDeleteView(generic.DeleteView, APIView):
    permission_classes = [IsStaff]
    model = Communities
    success_url = reverse_lazy('personal:community_manager')
    template_name = "staffapplication/pages/managers/update-job/confirm-delete.html"

    def delete(self, request, *args, **kwargs):
        # self.object = form.save()
        self.object = self.get_object()
        success_url = self.get_success_url()
        CommunityHistory(communityid=self.object.slug, user=self.request.user, job='D').save()
        self.object.delete()
        return HttpResponseRedirect(success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['communityback'] = True
        return context


class ReferenceHistoryView(generic.ListView, APIView):
    permission_classes = [IsStaff]
    model = References
    template_name = "staffapplication/pages/managers/update-job/content-history.html"
    context_object_name = "changeCollection"
    paginate_by = 10

    def get_queryset(self):
        history = ReferenceHistory.objects.filter(referenceid=self.kwargs['pk'])
        return history

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['referenceback'] = True
        return context


class ReferenceUpdateView(generic.UpdateView):
    permission_classes = [IsStaff]
    model = References
    # fields = ['title', 'references', 'description', 'body', 'image', 'community']
    template_name = "staffapplication/pages/managers/update-job/update-form.html"
    success_url = reverse_lazy('personal:reference_manager')
    form_class = ReferencesForm

    def post(self, request, *args, **kwargs):
        token = get_token_from_cookie(request)
        try:
            token = Token.objects.get(key=token)
            request.user = token.user
            return super(ReferenceUpdateView, self).post(request, **kwargs)
        except Token.DoesNotExist:
            return HttpResponse("response.401", status=401)

personal/views.py
from django.shortcuts import render

# Create your views here.

personal/templates/staffapplication/pages/managers/blog-manager.html
{% extends "staffapplication/base.html" %}
{% block panel_block %}
    {% load widget_tweaks %}

    {% if messages %}
        {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}{{ message.tags }}{% endif %}{% endif %}" role="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}

    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <div class="btn-group-sm">
                    <button class="btn btn-light mr-2" id="add">Add</button>
                    <button class="btn btn-light mr-2" id="update">Update</button>
                </div>
            </div>
        </div>
    </div>

    <div class="add-blog">
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Blog</h4>
                <p class="card-description"> Add </p>
                <form class="forms-sample" method="post" enctype="multipart/form-data" action="{% url 'personal:add_blog' %}">
                    {% csrf_token %}
                    {% for field in blogForm.visible_fields %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {% render_field field class="form-control" %}
                    </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-gradient-primary mr-2">Submit</button>
                </form>
              </div>
            </div>
        </div>
    </div>

    <div class="update-blog" style="display: none">
        <div class="col-12 grid-margin">
            <div class="card">
                <div class="card-body">
                    <div class="search-bar">
                        <form class="d-flex align-items-center h-100" method="get" id="blog-search">
                          <div class="input-group">
                            <div class="input-group-prepend bg-transparent">
                              <i class="input-group-text border-0 mdi mdi-magnify"></i>
                            </div>
                            <input type="text" name="search" class="form-control bg-transparent border-0" placeholder="Give title or description of blog">
                          </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="blogcontainer" id="content-container">
                <div class="row">

                </div>
                <div class="btn-group-sm" id="pagination-button" >
                    <a class="btn btn-light disabled" href="#" id="prev-page" >&laquo;</a>
                    <a class="btn btn-light disabled" href="#" id="next-page" >&raquo;</a>
                </div>
        </div>


    </div>
{% endblock %}

{% block footer %}
    {% load static %}
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

    {{ blogForm.media }}
{% endblock %}

{% block custom_scripts %}
    <script>
        "use strict";
        //Using session storage for back function
        var saveData = function() {
            if (!sessionStorage)
                return;
            var data = {
                // id: id,
                // scroll: $("#PostItemContainer").scrollTop(),
                html: $("#content-container").html()
            };
            console.log(data);
            sessionStorage.setItem("list_html",JSON.stringify(data));
        };

        var restoreData = function() {
            if (!sessionStorage)
                return;
            var data = sessionStorage.getItem("list_html");
            // console.log(data);
            if (!data)
                return null;
            return JSON.parse(data);
        };


        function send_request(search){

            $.get(search, (data) => {
                let container = document.getElementsByClassName("row")[0];
                container.innerHTML = "";
                console.log(data);
                for(var i in data.results ) {
                    let blog = data.results[i];
                    let item = document.createElement("div");
                    item.setAttribute("class","card");
                    item.setAttribute("style","width: 18rem; margin: 1rem");
                    item.innerHTML  = '<img src="'+blog.image+'" style="width:100%" class="card-img-top">'+
                                    '<div class="card-body">'+
                                    '<h4 class="card-title">'+blog.title+'</h4>'+
                                    '<p class="card-text">' + blog.description +'</p>'+
                                     // TODO Try to make these urls dynamic
                                    '<a href= "api/personal/staffhome/editblog/'+blog.slug+'" class="card-link"><i class="mdi mdi-lead-pencil mdi-24px"></i></a>'+
                                    '<a href="api/personal/staffhome/deleteblog/'+blog.slug+'" class="card-link"><i class="mdi mdi-delete mdi-24px"></i></a>'+
                                    '<a href="api/personal/staffhome/bloghistory/'+blog.slug+'" class="card-link"><i class="mdi mdi-history mdi-24px"></i></a>'+
                                    '</div>';
                    container.appendChild(item);

                }
                if( data.next ){
                    $("#next-page").attr("href", data.next);
                    $("#next-page").attr("class","btn btn-light");
                }else{
                    $("#next-page").attr('href', '#');
                    $("#next-page").attr("class","btn btn-light disabled");
                }

                if( data.previous ){
                    $("#prev-page").attr("href", data.previous);
                    $("#prev-page").attr("class","btn btn-light");
                }else {
                    $("#prev-page").attr('href', '#');
                    $("#prev-page").attr("class","btn btn-light disabled");
                }

                saveData();

            });
        }

        $( () => {

            //TODO this setting is for django CORS which is not working correctly, make it work
            $.ajaxSetup({xhrFields: { withCredentials: true } });
            let page = 1;

            $("#add").on('click', () => {
                 $(".add-blog").show();
                 $(".update-blog").hide();
            });
            $("#update").click(() => {
                 $(".add-blog").hide();
                 $(".update-blog").show();
            });


            $("#blog-search").submit((event) => {
                event.preventDefault();
                let search = "{% url 'personal:blog-list' %}?page="+page+"&"+$("#blog-search").serialize();
                send_request(search);
            });

            //back button feature
            {% if back %}
                $(".add-blog").hide();
                $(".update-blog").show();
                let data = restoreData();
                if( data )
                    $("#content-container").html(data.html);
                console.log(data);
            {% else %}
                //Default show all
                let search = "{% url 'personal:blog-list' %}?page="+page+"&"+$("#blog-search").serialize();
                send_request(search);
            {% endif %}

            //This is jquery delegation event handling for back button feature
            $("#pagination-button").on( 'click','#next-page', (event) => {
                event.preventDefault();
                send_request($(event.target).attr('href'));
                return false
            });

            //This is jquery delegation event handling for back button feature
            $("#pagination-button").on( 'click', '#prev-page', (event) => {
                event.preventDefault();
                send_request($(event.target).attr('href'));
                return false;
            });

        });



    </script>
{% endblock %}

personal/templates/staffapplication/pages/managers/staff-manager.html
{% extends "staffapplication/base.html" %}
{% block panel_block %}
    {% load widget_tweaks %}
    {{ staffRemoveForm.form.media }}

    {% if messages %}
        {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}{{ message.tags }}{% endif %}{% endif %}" role="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}

    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <div class="btn-group-sm">
                    <button class="btn btn-light mr-2" id="add">Add</button>
                    <button class="btn btn-light mr-2" id="remove">Remove</button>
                </div>
            </div>
        </div>
    </div>
    <div class="add-staff">
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Staff</h4>
                <p class="card-description"> Add </p>
                <form class="forms-sample" method="post" enctype="multipart/form-data" action="{% url 'personal:add_staff' %}">
                    {% csrf_token %}
                    {% for field in staffCreateForm.visible_fields %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {% render_field field class="form-control" %}
                    </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-gradient-primary mr-2">Submit</button>
                </form>
              </div>
            </div>
        </div>
    </div>
    <div class="remove-staff" style="display: none">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <form method="get" id="form-remove-staff">
                    <div class="well">
                      <h4 style="margin-top: 0">Filter</h4>
                      <div class="row">
                        {% for field in staffRemoveForm.visible_fields %}
                            <div class="form-group col-sm-4 col-md-3">
                                {{ field.label_tag }}
                                {% render_field field class="form-control" %}
                            </div>
                        {% endfor %}
                      </div>
                      <button type="submit" class="btn btn-primary">
                        <span class="glyphicon glyphicon-search"></span> Search
                      </button>
                    </div>
                </form>

                  <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th>First name</th>
                        <th>Last name</th>
                        <th>Mobile Number</th>
                        <th>Date joined</th>
                        <th>Remove</th>
                      </tr>
                    </thead>
                    <tbody id="staff-table">

                    </tbody>
                  </table>

              </div>
            </div>
        </div>

    </div>
{% endblock %}

{% block footer %}
    {% load static %}
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    {{ staffRemoveForm.media }}

{% endblock %}
{% block custom_scripts %}
    <script>
        $(() => {

            $("#add").on('click', () => {
                 $(".add-staff").show();
                 $(".remove-staff").hide();
            });
            $("#remove").click(() => {
                 $(".add-staff").hide();
                 $(".remove-staff").show();
            });

            $("#form-remove-staff").submit((event) => {
                event.preventDefault();
                page = 1;
                let search_url = "{% url 'personal:staff-list' %}?page="+page+"&"+$("#form-remove-staff").serialize();
                $.get(search_url, (data) =>{
                    $("#staff-table").empty();

                   for( var i in data.results ){
                    let row = document.createElement("tr");
                    let staff = data.results[i];
                    let delete_url = "{% url 'personal:staff_remove' 1 %}";
                    delete_url = delete_url.replace('1', staff.pk);
                    row.innerHTML = "<td>"+ staff.first_name + "</td>" +
                        "<td>" + staff.last_name + "</td>" +
                        "<td>" + staff.mobile_number + "</td>"+
                        "<td>" + staff.date_joined + "</td>"+
                        "<td><a class='btn btn-light remove-staff-button' href="+ delete_url +">Remove</a></td>";
                    $("#staff-table").append(row);
                   }
                   $(".remove-staff-button").unbind("click");
                   $(".remove-staff-button").click((e) => {
                       e.preventDefault();
                       let url = $(e.target).attr("href");
                       if (confirm("Sure You Want To Delete!")) {
                           $.post(url,(data) => {
                                if( data['response'] === "success" ){
                                    alert("Successfully Removed Staff");
                                    $("#form-remove-staff").submit();
                                }else{
                                    alert("We are facing some issues. Try again later");
                                }
                           })
                       }

                    })
               })

            })
        });
    </script>

{% endblock %}