account/api/urls.py
from django.urls import re_path
from .views import get_account_properties, OTPGenerator, OTPAuthenticate, Login, Logout, update_account_properties


app_name = 'account'

urlpatterns = [
    re_path(r'^getOTP/$', OTPGenerator.as_view(), name='get_otp'),
    re_path(r'^authOTP/$', OTPAuthenticate.as_view(), name='auth_otp'),
    re_path(r'^login/$', Login.as_view(), name='login'),
    re_path(r'^logout/$', Logout.as_view(), name='logout'),
    re_path(r'^accountProperties/$', get_account_properties, name='account_properties'),
    re_path(r'^updateAccountProperties/$', update_account_properties, name='update_account_properties'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler400, handler403, handler404, handler500
from personal.api import views as personal_views
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

api_info = openapi.Info(
      title="Brainonet API",
      default_version='v1',
      description="Application API's",
      terms_of_service="https://www.brainonet.com/policies/terms/",
      contact=openapi.Contact(email="contact@brainonet.com"),
      license=openapi.License(name="BSD License"),
   )
schema_view = get_schema_view(
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),

    # REST
    path('api/account/', include('account.api.urls', 'account_api')),
    path('api/blog/', include('blog.api.urls', 'blog_api')),
    path('api/communities/', include('communities.api.urls', 'community_api')),
    path('api/expose/', include('expose.api.urls', 'expose_api')),
    path('api/exposeunits/', include('exposeunits.api.urls', 'exposeunit_api')),
    path('api/personal/', include('personal.api.urls', 'personal_api')),
    path('api/groupchat/', include('groupchat.api.urls', 'groupchat_api')),
    path('api/recommend/', include('recommend.api.urls', 'recommendation_api')),
    path('api/commons/', include('commons.api.urls', 'commons_api')),

    # path('api/', schema_view),

    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    # AutoComplete
    # re_path(r'^select2/', include('django_select2.urls')),

]

handler400 = personal_views.error_400
handler404 = personal_views.error_404
handler403 = personal_views.error_403
handler500 = personal_views.error_500

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal/api/urls.py
from django.urls import re_path, path, include
from .views import *
from blog.api.views import ApiReferenceListView, ApiBlogListView
from communities.api.views import ApiCommunityListView

app_name = "personal"

urlpatterns = [

    re_path(r"^$", stafflogin_view, name="staff_login"),
    re_path(r"^staffhome/$", staffhome_view, name="staff_home"),

    re_path(r"^staffhome/blog-manager/$", blog_manager_view, name="blog_manager"),
    re_path(r"^staffhome/community-manager/$", community_manager_view, name="community_manager"),
    re_path(r"^staffhome/reference-manager/$", reference_manager_view, name="reference_manager"),

    re_path(r"^staffhome/addblog/$", uploadblog, name="add_blog"),
    re_path(r"^staffhome/addreferences/$", uploadreferences, name="add_references"),
    re_path(r"^staffhome/addcommunity/$", uploadcommunity, name="add_community"),

    # re_path(r"^staffhome/showblogs/$", BlogHomeView.as_view(), name="show_blog"),
    # re_path(r"^staffhome/showcommunity/$", CommunityHomeView.as_view(), name="show_community"),
    re_path(r"^staffhome/showaccounts/$", UserListView.as_view(), name="show_account"),

    re_path(r"staffhome/editblog/(?P<slug>[\w-]+)/", BlogUpdateView.as_view(), name="edit_blog"),
    re_path(r"staffhome/deleteblog/(?P<slug>[\w-]+)/", BlogDeleteView.as_view(), name="delete_blog"),
    re_path(r"staffhome/editcommunity/(?P<slug>[\w-]+)/", CommunityUpdateView.as_view(), name="edit_community"),
    re_path(r"staffhome/deletecommunity/(?P<slug>[\w-]+)/", CommunityDeleteView.as_view(), name="delete_community"),
    re_path(r"staffhome/editreference/(?P<pk>[\w-]+)/", ReferenceUpdateView.as_view(), name="edit_reference"),
    re_path(r"staffhome/deletereference/(?P<pk>[\w-]+)/", ReferenceDeleteView.as_view(), name="delete_reference"),

    re_path(r"staffhome/communityhistory/(?P<slug>[\w-]+)/", CommunityHistoryView.as_view(), name="community_history"),
    re_path(r"staffhome/bloghistory/(?P<slug>[\w-]+)/", BlogHistoryView.as_view(), name="blog_history"),
    re_path(r"staffhome/referencehistory/(?P<pk>[\w-]+)/", ReferenceHistoryView.as_view(), name="reference_history"),

    re_path(r"staffhome/logout", stafflogout, name="staff_logout"),
    re_path(r"^staffhome/users_autocomplete/$", UsersAutocomplete.as_view(), name="users_autocomplete"),
    re_path(r"^staffhome/references_autocomplete/$", ReferencesAutocomplete.as_view(create_field='refers'),
            name="references_autocomplete"),

    re_path(r"^staffhome/imagefaketool$", fakenews_home, name="fake_toolkit"),
    re_path(r"^staffhome/imagefakesearch$", fakenews_image_search, name="fake_image_search"),
    re_path(r"^staffhome/imagedataset$", fakenews_image_dataset, name="fake_image_dataset"),

    re_path(r"^staffhome/staff-manager/$", staff_manager_view, name="staff_manager"),
    re_path(r"^staffhome/addstaff/$", addstaff, name="add_staff"),
    re_path(r"^staffhome/staff_autocomplete_mobile/$", StaffAutocompleteMobile.as_view(), name="staff_autocomplete_mobile"),
    re_path(r"^staffhome/staff_autocomplete_fname/$", StaffAutocompleteFname.as_view(), name="staff_autocomplete_fname"),
    re_path(r"^staffhome/staff_autocomplete_lname/$", StaffAutocompleteLname.as_view(), name="staff_autocomplete_lname"),
    re_path(r"^staffhome/staff-remove/(?P<pk>[\w-]+)$", staff_delete_view, name="staff_remove"),
    re_path(r"^staffhome/staff-list/$", ApiStaffListView.as_view(), name="staff-list"),

    # CORS not working, this is a hack so that cookie is passed to same domain for ajax
    re_path(r"^staffhome/blog-list$", ApiBlogListView.as_view(), name="blog-list"),
    re_path(r"^staffhome/reference-list$", ApiReferenceListView.as_view(), name="reference-list"),
    re_path(r"^staffhome/community-list$", ApiCommunityListView.as_view(), name="community-list"),

]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
import rest_framework.authtoken.models
from django.utils.translation import gettext_lazy as _
import rest_framework.authentication
import hashlib


def upload_location(instance, filename, **kwargs):
    mobile_hash = hashlib.md5(instance.mobile_number.encode('utf-8')).hexdigest()
    file_path = 'account/profileimage/{first_name}-{last_name}-{hash}-{filename}'.format(
        first_name=str(instance.first_name), last_name=str(instance.last_name), hash=str(mobile_hash),
        filename=filename
    )
    return file_path


class MyAccountManager(BaseUserManager):

    def create_user(self, mobile_number, password=None):
        if not mobile_number:
            raise ValueError('User must have a mobile number')

        user = self.model(
            mobile_number=mobile_number,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, mobile_number, password):
        user = self.create_user(
            password=password,
            mobile_number=mobile_number
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    first_name = models.CharField(verbose_name="first name", max_length=30, default='')
    last_name = models.CharField(verbose_name="last name", max_length=30, default='')
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    mobile_number = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=200, default="")
    karma = models.PositiveIntegerField(default=0)
    profile_image = models.ImageField(upload_to=upload_location, null=False, blank=True)

    USERNAME_FIELD = 'mobile_number'
    # REQUIRED_FIELDS = ['']

    objects = MyAccountManager()

    class Meta:
        ordering = ['date_joined']

    def __str__(self):
        return self.mobile_number

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True


class Group(models.Model):
    group_name = models.CharField(max_length=20, unique=True)


class MemberShip(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    date_joined = models.DateTimeField(verbose_name="date joined", auto_now_add=True)


class Authi(models.Model):
    mobile_number = models.CharField(max_length=20)
    otp = models.CharField(max_length=20, null=True)


class Token(rest_framework.authtoken.models.Token):
    # key is no longer primary key, but still indexed and unique
    key = models.CharField(_("Key"), max_length=40, primary_key=True)
    # relation to user is a ForeignKey, so each user can have more than one token
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='auth_tokens',
        on_delete=models.CASCADE, verbose_name=_("User")
    )
    # name = models.CharField(_("Name"), max_length=64)

    class Meta:
        unique_together = (('user', 'key'),)


class TokenAuthentication(rest_framework.authentication.TokenAuthentication):
    model = Token

    def authenticate(self, request):
        if 'Authorization' in request.COOKIES:
            # print(request.COOKIES['Authorization'].encode("utf-8"))
            token = request.COOKIES.get("Authorization")
            print(token)
            if token:
                token = token.replace("Token%20", "")
            print(token)
            return self.authenticate_credentials(token)

        return super().authenticate(request)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

personal/models.py
from django.db import models

# Create your models here.

personal/views.py
from django.shortcuts import render

# Create your views here.

personal/templates/staffapplication/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Brainonet</title>
    <!-- plugins:css -->
    {% load staticfiles %}
      <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
      <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
      <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
      <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />

    {% load widget_tweaks %}
  </head>
  <body>

    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth">
          <div class="row flex-grow">
            <div class="col-lg-4 mx-auto">
              <div class="auth-form-light text-left p-5">
                <div class="brand-logo">
                  <img src="{% static 'assets/images/logo_white.svg' %}">
                </div>
                <h4><span id="msg">Hello! let's get started</span></h4>
                <h6 class="font-weight-light">Sign in to continue.</h6>

<!--                Otp Generator Form-->
              <div id="mobileFormContainer">

                <form class="pt-3" id="mobileForm">
                {% for field in mobileForm.visible_fields %}
                  <div class="form-group">
                      {{ field.label_tag }}
                      {% render_field field class="form-control form-control-lg" %}
                  </div>
                {% endfor %}
                  <button type="submit" class="btn btn-primary">SIGN IN</button>

                  <div class="text-center mt-4 font-weight-light"> Don't have an account? <a href="#" class="text-primary">Contact here</a>
                  </div>
                </form>
              </div>

<!--                Otp Verification Form-->
              <div id="otpFormContainer" style="display: none">

                <form class="pt-3" id="otpForm">
                {% for field in otpForm.visible_fields %}
                  <div class="form-group">
                      {{ field.label_tag }}
                      {% render_field field class="form-control form-control-lg" %}
                  </div>
                {% endfor %}

                  <div class="btn-group-sm">
                    <button type="submit" class="btn btn-primary">Verify</button>
                    <button class="btn btn-primary" id="resendOTP">Resend OTP</button>
                  </div>

                  <div class="my-2 d-flex justify-content-between align-items-center">
                    <div class="form-check">
                      <label class="form-check-label text-muted">
                        <input type="checkbox" class="form-check-input" id="keep"> Keep me signed in </label>
                    </div>
                  </div>
                </form>
              </div>

<!--              On Success Submit  -->
              <div id="staffHomeContainer" style="display: none">
                  <form method="get" id="staffHomeForm" action="{% url 'personal:staff_home' %}">
                      {% csrf_token %}

                  </form>
              </div>

              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>

    <!-- container-scroller -->
    <!-- plugins:js -->
    {% load staticfiles %}
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <script src="{% static 'assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'assets/js/misc.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
    <!-- endinject -->


<!--    Script for OTP generation and verification-->
    <script>

      $(document).ready(() => {
          console.log($.cookie("Authorization"));
          console.log($.cookie('User'));

          if( $.cookie("Authorization") && $.cookie('User') ){
            $("#staffHomeForm").submit();
          }


          $("#mobileForm").on("submit", (event) =>{
              console.log($("#id_number").val());
              event.preventDefault();

              $.ajax({
                  type:"POST",
                  cache:"false",
                  //contentType : "application/json",//type of data being send to server
                  url:"{% url 'account:get_otp' %}",
                  data : { 'phoneNumber': $("#id_number").val() },
                  // dataType : "json",//result expected from server
                  //                 //with json return type we can return java objects
                  //                 //With text we can return String from java conroller
                  timeout:100000,
                  success:function(data){
                      console.log(data);

                      if( data['response'] === 'success' ){
                          $("#otpFormContainer").show();
                          $("#mobileFormContainer").hide();
                          $("#msg").text("Check Your Mobile for OTP");
                      }
                      else {
                          $("#msg").text(data['error_message']);


                      }
                  },
                  error: function(e){
                      $("#msg").text("Some problem occured, Please retry");
                      console.log(e);
                  },

              });
          });

          $("#otpForm").submit((event) => {

              event.preventDefault();

              $.ajax({

                  type:"POST",
                  cache:"false",
                  url:"{% url 'account:auth_otp' %}",
                  headers: {
                    "IsCMS": "True",
                  },
                  timeout:100000,
                  contentType : "application/json",//type of data being send to server
                  data : JSON.stringify({mobile_number: $("#id_number").val(), otp: $("#id_otp").val()}),

                  success:function(data){
                      console.log(data);
                      if(data["response"] === "success") {
                          console.log(data['token'].trim());
                          let user={};
                          user.firstname = data['first_name'];
                          user.lastname = data['last_name'];
                          user.role = data['role'];
                          if( $('#keep').is(':checked') ){

                          $.cookie('Authorization', "Token ".concat(data['token'].trim()),
                                  { expires: 14 });
                          $.cookie('User', JSON.stringify(user), { expires: 14 });
                          } else {
                            $.cookie('Authorization', "Token ".concat(data['token'].trim()));
                            $.cookie('User', JSON.stringify(user));
                          }
                          $("#staffHomeForm").submit();

                      } else{
                          $("#msg").text(data["error_message"]);
                      }


                  },
                  error: function(e){
                      console.log(e);
                  },

              });
          });

          $("#resendOTP").click(() => {
              $("#otpFormContainer").hide();
              $("#mobileFormContainer").show();
          })
      });

    </script>

  </body>
</html>